config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#landing', as: :landing

  get '/home' => "pages#home", as: :home

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'users' => 'users#index', as: :users
  get 'user/new' => 'users#new', as: :new_user
  get 'user/account' => 'users#user_account'
  get 'user/:user_id' => 'users#show', as: :user
  post 'users' => 'users#create'
  get "user/:user_id/edit" => "users#edit", as: :edit_user
  patch "user/:user_id" => "users#update"
  delete 'user/:user_id' => 'users#destroy'

  get 'portfolios' => 'portfolios#index', as: :portfolios
  get 'user/:user_id/edit_portfolios' => 'portfolios#edit_portfolios', as: :edit_portfolios_page
  get 'user/:user_id/portfolios' => 'portfolios#show_user_portfolios', as: :user_portfolios
  get 'user/:user_id/portfolio/new' => 'portfolios#new', as: :new_portfolio
  post 'portfolios' => 'portfolios#create'
  get 'user/:user_id/portfolio/:id' => 'portfolios#show', as: :portfolio
  get 'user/:user_id/portfolio/:id/edit' => 'portfolios#edit', as: :edit_portfolio
  patch 'portfolios' => 'portfolios#update'
  delete 'user/:user_id/portfolio/:id' => 'portfolios#destroy'

  get 'photo/:photo_id' => 'photos#show', as: :photo

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/views/shared/_delete_portfolio.html.erb
<div class='row'>
    <div class="col-md-8 col-md-offset-2 text-center">
    	<div class="text-center">
        	<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deletePortfolioModal">
                Delete Portfolio
            </button>
        </div>
    <div>
</div>


<!-- Modal -->
<div class="modal fade" id="deletePortfolioModal" tabindex="-1" role="dialog" aria-labelledby="deletePortfolioLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <h4 class="modal-title" id="myModalLabel">Delete Portfolio</h4>
            </div>
            <div class="modal-body">
                <h4>Your portfolio will be deleted forever.  Are you sure?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <%= link_to "Delete", portfolio_path, method: :delete, class: "btn btn-danger"  %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_flash_messages.html.erb
<!-- Flash Messages -->
<% flash.each do |type, msg| %>
    <% if type=='notice' %>
        <%= content_tag :div, msg, class:"alert alert-success", role:"alert"  %>
    <% elsif type=='error' %>
        <%= content_tag :div, msg, class:"alert alert-warning", role:"alert" %>
    <% end %>
<% end %>

<!-- Error message from model validations -->
<!-- User Model -->
<% unless @user.nil? || @user.errors.empty?%>
    <div class="alert alert-warning", role="alert">
        <ul>
            <% @user.errors.full_messages.each do |msg| %> 
                <li><%= msg %></li>
            <% end %> 
        </ul>
    </div>
<% end %>

<!-- Portfolio Model -->
 <% unless @portfolio.nil? || @portfolio.errors.empty?%>
    <div class="alert alert-warning", role="alert">
        <ul>
            <% @portfolio.errors.full_messages.each do |msg| %> 
                <li><%= msg %></li>
            <% end %> 
        </ul>
    </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
	<%= link_to	"As of Today", home_path, class: "btn btn-link", id: "home-button" %>

	<% if logged_in? %>
        <%= link_to 'Log Out', logout_path, method: :delete, class: 'btn btn-primary nav-button-right' %>

        <div class="dropdown nav-button-right">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                More
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a role="menuitem" tabindex="-1" href=<%= user_portfolios_path(current_user) %>>My Portfolios</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href=<%= edit_portfolios_page_path(current_user) %>>Edit Portfolios</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href=<%= new_portfolio_path(current_user) %>>New Portfolio</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href=<%= user_path(current_user) %>>My Profile</a></li>
                <li role="presentation" class="divider"></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href=<%= edit_user_path(current_user) %>>Edit Profile</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href=<%= user_account_path %>>Account</a></li>
            </ul>
        </div>
 			
 	<% else %>
		<span class= "nav-button-right">
  			<%= link_to 'Log In', login_path, class: 'btn btn-info' %>
  		</span>
  		
 		<span class= "nav-button-right">
			<%= link_to "Create Account", new_user_path, class: 'btn btn-primary'  %>
		</span>
	<% end %>
</nav>

app/views/shared/_page_header.html.erb
<div class='page-header'>
	<h1 id='page-header-h1'>As of Today</h1>
	<h4 class='text-center'>A Wedding Photographer Hub</h4>
</div>

app/views/shared/_user_profile_header.html.erb
<div>
    <%= link_to (image_tag(user_profile_pic(@user), class: "img-thumbnail img-responsive", id:"user_portfolio_profile_pic")), user_portfolios_path(@user) %> 
    <div id="user_portfolios">
        <h2>
            <%= @user.first_name %> <%= @user.last_name %>
        </h2>
        <p><%= link_to "View Portfolios", user_portfolios_path(@user) %></p>
        <p><%= link_to "Profile", user_path(@user) %></p>
    </div>
</div>