config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#landing', as: :landing

  get '/home' => "pages#home", as: :home

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'users' => 'users#index', as: :users
  get 'user/new' => 'users#new', as: :new_user
  get 'user/account' => 'users#user_account'
  get 'user/:user_id' => 'users#show', as: :user
  post 'users' => 'users#create'
  get "user/:user_id/edit" => "users#edit", as: :edit_user
  patch "user/:user_id" => "users#update"
  delete 'user/:user_id' => 'users#destroy'

  get 'portfolios' => 'portfolios#index', as: :portfolios
  get 'user/:user_id/edit_portfolios' => 'portfolios#edit_portfolios', as: :edit_portfolios_page
  get 'user/:user_id/portfolios' => 'portfolios#show_user_portfolios', as: :user_portfolios
  get 'user/:user_id/portfolio/new' => 'portfolios#new', as: :new_portfolio
  post 'portfolios' => 'portfolios#create'
  get 'user/:user_id/portfolio/:id' => 'portfolios#show', as: :portfolio
  get 'user/:user_id/portfolio/:id/edit' => 'portfolios#edit', as: :edit_portfolio
  patch 'portfolios' => 'portfolios#update'
  delete 'user/:user_id/portfolio/:id' => 'portfolios#destroy'

  get 'photo/:photo_id' => 'photos#show', as: :photo

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/views/pages/home.html.erb
<div class='justified-container'>
    <% @photos.each do |photo| %>
            <%= link_to image_tag(photo.photo_image.url(:normal), class: "center-block"), photo_path(photo.id) %>
    <% end %>
</div>

app/views/pages/landing.html.erb
<div id="tinted-layer"></div><div>

<%= render "shared/navigation" %>

<div class="row">
    <div class="col-md-4 col-md-offset-4 text-center" id="landing-cta">
        <h1>As of Today</h1>
        <h4 class='text-center'>Discover the photographer to capture<br>the precious moments of your wedding day</h4>
        <%= link_to "Discover", home_path, class: "btn btn-primary" %>
    </div>
</div>

<script>
$(function() {


    var H = $(window).height();
    $('#landing-page-main-container').height(H);

    function imgsize() {
        var H = $(window).height(); // Consider navbar height
        $('#landing-page-main-container').height(H);
    }
    // Resize image when browser size changes
    $(window).bind('resize', function() { imgsize(); });

});
</script>